### ISSUE TITLE
Invalid Python markers for pytest-mypy?

### ISSUE THREAD

**Issue by pawamoy** [jaraco/backports.entry_points_selectable#2]
Hello @jaraco,

Is this marker correct?

```
pytest-mypy; python_implementation != "PyPy" and python_version < "3.10" and python_version > "3"
```

Poetry resolves it to `<3.10 and >=4`.
Shouldn't you write `>= "3"` instead?

For reference: https://github.com/python-poetry/poetry/issues/3862

**Comment by pawamoy** [comment]
Hmmm it seems your markers are correct based on PEP508 and PEP440:

```python
>>> import packaging
>>> from packaging import version
>>> version.parse("3.6") > version.parse("3")
True
```

**Comment by jaraco** [comment]
Thanks for reporting this, and I'm glad I uncovered a mismatch in poetry.

Question: Now that poetry has fixed the issue, would there still be value in this project declaring `>=3` to add support for older poetry versions, or do most users run the latest poetry and it's not worth the trouble?

**Comment by pawamoy** [comment]
Er, I'm honestly not sure :sweat_smile: 
If Poetry releases the fix soon as 1.1.6, it might not be that useful. If it takes longer (and it could), more and more libs that depends on other libs using these markers could be subject to this, and impact a lot of users. By the way it's not that easy to identify such libs. So yeah, it might be worth the trouble :slightly_smiling_face:

**Comment by hukkin** [comment]
I went ahead and opened a [PR](https://github.com/jaraco/backports.entry_points_selectable/pull/3) for this before realizing this closed issue existed.

I think specifying the dependencies as `>= 3` makes more sense even if the Poetry issue is fixed. As far as I know `>3` is equivalent to `>=3 and !=3`. Feels a bit strange to me to arbitrarily exclude Python version 3.0.0 (but not 3.0.1 for instance).

**Comment by jaraco** [comment]
Version 1.0.4 has the patch.
